export const primaryColor = '#400090'
export const white = '#fff'
export const lightPurple = '#7c53c3'
export const lightGray = '#f2f2f2'
export const ultraLightPurple = '#f1ecf8'
export const red = '#d9534f'
export const green = '#5cb85c'